# Project information
site_name: Floki
site_url: https://cyb3rward0g.github.io/floki
site_author: Cyb3rWard0g
site_description: Agentic Workflows Made Simple
strict: false

# Repository
repo_name: Cyb3rWard0g/floki
repo_url: https://github.com/Cyb3rWard0g/floki
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 Cyb3rWard0g

theme:
  name: material
  logo: 'logo-black.svg'
  favicon: 'favicon.png'
  icon:
    repo: fontawesome/brands/github 
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.code.select
    - content.tooltips
    - announce.dismiss
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.suggest
    - toc.follow

plugins:
  - search
  - social
  - mkdocs-jupyter:
      # ignore_h1_titles: true
      execute: false

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  version:
    provider: mike
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Cyb3rWard0g/floki
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/floki-ai/
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/Cyb3rWard0g

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home:
    - Home: index.md
    - Why Floki: home/why.md
    - Core Principles: home/principles.md
    - Installation: home/installation.md
    - Quickstarts:
      - Quickstarts: home/quickstarts/index.md
      - LLM Inference Client: home/quickstarts/llm.md
      - AI Agents: home/quickstarts/agents.md
      - Dapr & Floki Workflows: home/quickstarts/dapr_workflows.md
      - LLM-based Task Workflows: home/quickstarts/llm_workflows.md
      - Multi-Agent Workflows: home/quickstarts/agentic_workflows.md
  - Core Concepts:
    - Agents: concepts/agents.md
    - Messaging: concepts/messaging.md
    - Text Splitter: concepts/text_splitter.md
    - Arxiv Fetcher: concepts/arxiv_fetcher.md