#
# Copyright 2026 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

services:
  workflow-agent:
    image: localhost:5001/workflow-agent:latest
    build:
      context: ../../
      dockerfile: ./quickstarts/05-multi-agent-workflow-k8s/services/workflow-agent/Dockerfile
  frodo:
    image: localhost:5001/frodo:latest
    build:
      context: ../../
      dockerfile: ./quickstarts/05-multi-agent-workflow-k8s/services/frodo/Dockerfile
  sam:
    image: localhost:5001/sam:latest
    build:
      context: ../../
      dockerfile: ./quickstarts/05-multi-agent-workflow-k8s/services/sam/Dockerfile
  gandalf:
    image: localhost:5001/gandalf:latest
    build:
      context: ../../
      dockerfile: ./quickstarts/05-multi-agent-workflow-k8s/services/gandalf/Dockerfile
  legolas:
    image: localhost:5001/legolas:latest
    build:
      context: ../../
      dockerfile: ./quickstarts/05-multi-agent-workflow-k8s/services/legolas/Dockerfile
