#!/usr/bin/env python3

"""
Environment Setup Script for OpenAI Streaming Examples

This script helps you create a .env file with your OpenAI API key
for the streaming examples.
"""

import os
from pathlib import Path


def create_env_file():
    """Create a .env file with OpenAI API key."""
    workspace_root = Path(__file__).parent
    env_file = workspace_root / ".env"
    
    print("🔧 OpenAI Streaming Environment Setup")
    print("=" * 40)
    
    # Check if .env already exists
    if env_file.exists():
        print(f"📄 .env file already exists at: {env_file}")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response not in ['y', 'yes']:
            print("✅ Keeping existing .env file")
            return
    
    # Get OpenAI API key
    print("\n🔑 OpenAI API Key Setup")
    print("Get your API key from: https://platform.openai.com/api-keys")
    
    api_key = input("Enter your OpenAI API key: ").strip()
    
    if not api_key:
        print("❌ No API key provided. Exiting.")
        return
    
    if not api_key.startswith('sk-'):
        print("⚠️  Warning: OpenAI API keys typically start with 'sk-'")
        response = input("Continue anyway? (y/N): ").strip().lower()
        if response not in ['y', 'yes']:
            print("❌ Setup cancelled")
            return
    
    # Create .env content
    env_content = f"""# OpenAI Configuration
# Generated by setup_env.py
OPENAI_API_KEY={api_key}

# Optional: Azure OpenAI Configuration (if using Azure OpenAI instead)
# AZURE_OPENAI_ENDPOINT=https://your-resource.openai.azure.com/
# AZURE_OPENAI_API_KEY=your_azure_openai_key_here
# AZURE_OPENAI_API_VERSION=2024-02-15-preview

# Optional: Development Settings
# DAPR_HTTP_PORT=3500
# DAPR_GRPC_PORT=50001
"""
    
    # Write .env file
    try:
        with open(env_file, 'w') as f:
            f.write(env_content)
        
        print(f"✅ Created .env file at: {env_file}")
        print(f"🔒 API key masked: {api_key[:8]}...{api_key[-4:]}")
        
        # Set permissions (readable only by owner)
        os.chmod(env_file, 0o600)
        print("🔐 Set file permissions to 600 (owner read/write only)")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return
    
    print("\n🚀 Next steps:")
    print("1. Start Dapr: ./start_dapr.sh --dev")
    print("2. Run examples:")
    print("   - python test_openai_agents_streaming.py")
    print("   - python test_openai_streaming.py")


def main():
    """Main function."""
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n❌ Setup cancelled by user")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")


if __name__ == '__main__':
    main() 